permissions:
  contents: write

name: Build Windows Binary

on:
  push:
    branches:
      - main
    paths:
      - run.py
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install pyinstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build with pyinstaller
        run: pyinstaller --onefile --noconsole run.py

      - name: Truncate commit hash
        id: vars
        shell: pwsh
        run: |
          $sha_short = git rev-parse --short HEAD
          echo "sha_short=$sha_short" >> $env:GITHUB_OUTPUT

      - name: Rename binary
        run: |
          Rename-Item -Path "dist/run.exe" -NewName "Buckshot_Roulette_Bot_${{ steps.vars.outputs.sha_short }}_windows.exe"

      - name: Create/Upload Draft Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.vars.outputs.sha_short }}
          name: "Nightly - ${{ steps.vars.outputs.sha_short }}"
          body: "This is an autogenerated release from commit [${{ github.sha }}](https://github.com/ftc-payton/Buckshot-Roulette-Bot/commit/${{ github.sha }}). Things may be broken or incomplete! If you're looking for the latest stable release, click [here](https://github.com/ftc-payton/Buckshot-Roulette-Bot/releases/latest)"
          prerelease: true
          artifacts: dist/Buckshot_Roulette_Bot_${{ steps.vars.outputs.sha_short }}_windows.exe
